name: Create Release for WoW Addon

on:
  push:
    tags:
      - "v*"  # Wird nur bei Tags mit dem Präfix "v" ausgelöst (z.B. v1.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create addon zip
      run: |
        mkdir -p release
        # Zip the entire folder for the addon
        zip -r release/SimpleWaypoint-v${{ github.ref_name }}.zip SimpleWaypoint/*

    - name: Upload release to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: SimpleWaypoint-v${{ github.ref_name }}.zip
        path: release/SimpleWaypoint-v${{ github.ref_name }}.zip

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: release/SimpleWaypoint-v${{ github.ref_name }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: SimpleWaypoint v${{ github.ref_name }}
        draft: false
        prerelease: false

